### ISSUE TITLE
Implement RFC-01 for changing the way cache middlewares are injected into the application

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi-community/plugin-rest-cache#65]
See the following RFC: https://github.com/strapi-community/strapi-plugin-rest-cache/discussions/64

Suggestion is to remove middleware injection via koa-router copy and mutation and use native Strapi APIs instead that are officially supported and recommended by the Strapi Team.
```[tasklist]
### Tasks
- [ ] Get comments on RFC
- [ ] Accept the RFC
- [ ] Plan out implemention
- [ ] Discuss if this should be a new major version (depending on breaking changes)
- [ ] Come to decision if breaking changes are required or not for version
- [ ] Begin implementation
- [ ] Release new version
```
